AdminUser.create!([
  {email: "admin_exec@example.com", encrypted_password: "$2a$10$Y3mYUDiSpIzwLjCPOsa7rOXO1XmL6ekHjC1WX45OuH.6Qp9rn3juu", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 42, current_sign_in_at: "2016-04-10 03:33:28", last_sign_in_at: "2016-04-08 13:35:18", current_sign_in_ip: "::1", last_sign_in_ip: "::1"}
])
# Checkin.create!([
#   {is_checked_in: false, user_id: 1, venue_id: 2},
#   {is_checked_in: true, user_id: 5, venue_id: 2},
#   {is_checked_in: true, user_id: 5, venue_id: 2},
#   {is_checked_in: true, user_id: 5, venue_id: 7},
#   {is_checked_in: true, user_id: 5, venue_id: 7},
#   {is_checked_in: true, user_id: 5, venue_id: 12},
#   {is_checked_in: true, user_id: 5, venue_id: 10},
#   {is_checked_in: true, user_id: 5, venue_id: 9},
#   {is_checked_in: true, user_id: 5, venue_id: 10},
#   {is_checked_in: true, user_id: 5, venue_id: 1},
#   {is_checked_in: true, user_id: 5, venue_id: 1},
#   {is_checked_in: true, user_id: 5, venue_id: 1},
#   {is_checked_in: true, user_id: 5, venue_id: 4},
#   {is_checked_in: true, user_id: 5, venue_id: 8},
#   {is_checked_in: true, user_id: 9, venue_id: 2},
#   {is_checked_in: true, user_id: 5, venue_id: 7},
#   {is_checked_in: true, user_id: 5, venue_id: 10},
#   {is_checked_in: true, user_id: 5, venue_id: 4},
#   {is_checked_in: true, user_id: 5, venue_id: 8},
#   {is_checked_in: true, user_id: 5, venue_id: 9},
#   {is_checked_in: true, user_id: 5, venue_id: 2},
#   {is_checked_in: true, user_id: 3, venue_id: 3},
#   {is_checked_in: true, user_id: 3, venue_id: 3},
#   {is_checked_in: true, user_id: 3, venue_id: 3},
#   {is_checked_in: true, user_id: 3, venue_id: 2},
#   {is_checked_in: true, user_id: 3, venue_id: 2},
#   {is_checked_in: true, user_id: 3, venue_id: 4},
#   {is_checked_in: true, user_id: 3, venue_id: 5},
#   {is_checked_in: true, user_id: 3, venue_id: 11},
#   {is_checked_in: true, user_id: 3, venue_id: 9},
#   {is_checked_in: true, user_id: 3, venue_id: 11},
#   {is_checked_in: true, user_id: 3, venue_id: 9},
#   {is_checked_in: true, user_id: 3, venue_id: 5},
#   {is_checked_in: true, user_id: 3, venue_id: 4},
#   {is_checked_in: true, user_id: 3, venue_id: 10},
#   {is_checked_in: true, user_id: 3, venue_id: 10},
#   {is_checked_in: true, user_id: 3, venue_id: 6},
#   {is_checked_in: true, user_id: 3, venue_id: 6},
#   {is_checked_in: true, user_id: 3, venue_id: 6},
#   {is_checked_in: true, user_id: 3, venue_id: 6},
#   {is_checked_in: true, user_id: 3, venue_id: 8},
#   {is_checked_in: true, user_id: 8, venue_id: 8},
#   {is_checked_in: true, user_id: 8, venue_id: 1},
#   {is_checked_in: true, user_id: 8, venue_id: 2},
#   {is_checked_in: true, user_id: 8, venue_id: 3},
#   {is_checked_in: true, user_id: 8, venue_id: 4},
#   {is_checked_in: true, user_id: 5, venue_id: 4},
#   {is_checked_in: true, user_id: 8, venue_id: 8},
#   {is_checked_in: true, user_id: 8, venue_id: 1},
#   {is_checked_in: true, user_id: 8, venue_id: 2},
#   {is_checked_in: true, user_id: 8, venue_id: 3},
#   {is_checked_in: true, user_id: 8, venue_id: 4},
#   {is_checked_in: true, user_id: 3, venue_id: 4},
#   {is_checked_in: true, user_id: 12, venue_id: 4},
#   {is_checked_in: true, user_id: 9, venue_id: 4},
#   {is_checked_in: true, user_id: 7, venue_id: 4},
#   {is_checked_in: true, user_id: 13, venue_id: 4},
#   {is_checked_in: true, user_id: 11, venue_id: 4},
#   {is_checked_in: true, user_id: 14, venue_id: 4},
#   {is_checked_in: true, user_id: 1, venue_id: 4},
#   {is_checked_in: true, user_id: 2, venue_id: 4},
#   {is_checked_in: true, user_id: 4, venue_id: 4},
#   {is_checked_in: true, user_id: 10, venue_id: 4},
#   {is_checked_in: true, user_id: 5, venue_id: 2},
#   {is_checked_in: true, user_id: 5, venue_id: 4},
#   {is_checked_in: true, user_id: 5, venue_id: 1},
#   {is_checked_in: true, user_id: 5, venue_id: 9},
#   {is_checked_in: true, user_id: 5, venue_id: 9},
#   {is_checked_in: true, user_id: 5, venue_id: 4},
#   {is_checked_in: true, user_id: 4, venue_id: 4},
#   {is_checked_in: true, user_id: 1, venue_id: 18},
#   {is_checked_in: true, user_id: 1, venue_id: 18},
#   {is_checked_in: true, user_id: 1, venue_id: 18},
#   {is_checked_in: true, user_id: 1, venue_id: 18},
#   {is_checked_in: true, user_id: 1, venue_id: 18},
#   {is_checked_in: true, user_id: 1, venue_id: 18},
#   {is_checked_in: true, user_id: 1, venue_id: 18},
#   {is_checked_in: true, user_id: 1, venue_id: 18},
#   {is_checked_in: true, user_id: 7, venue_id: 18},
#   {is_checked_in: true, user_id: 16, venue_id: 14},
#   {is_checked_in: true, user_id: 5, venue_id: 14},
#   {is_checked_in: true, user_id: 7, venue_id: 14},
#   {is_checked_in: true, user_id: 8, venue_id: 14},
#   {is_checked_in: true, user_id: 5, venue_id: 4},
#   {is_checked_in: true, user_id: 5, venue_id: 1},
#   {is_checked_in: true, user_id: 5, venue_id: 1},
#   {is_checked_in: true, user_id: 5, venue_id: 3},
#   {is_checked_in: true, user_id: 5, venue_id: 14},
#   {is_checked_in: true, user_id: 5, venue_id: 4},
#   {is_checked_in: true, user_id: 4, venue_id: 4},
#   {is_checked_in: true, user_id: 17, venue_id: 14},
#   {is_checked_in: true, user_id: 5, venue_id: 14},
#   {is_checked_in: true, user_id: 3, venue_id: 8},
#   {is_checked_in: true, user_id: 5, venue_id: 4},
#   {is_checked_in: true, user_id: 5, venue_id: 8},
#   {is_checked_in: true, user_id: 18, venue_id: 17},
#   {is_checked_in: true, user_id: 1, venue_id: 18},
#   {is_checked_in: true, user_id: 1, venue_id: 18},
#   {is_checked_in: true, user_id: 1, venue_id: 2},
#   {is_checked_in: true, user_id: 1, venue_id: 2},
#   {is_checked_in: true, user_id: 1, venue_id: 2},
#   {is_checked_in: true, user_id: 1, venue_id: 18},
#   {is_checked_in: true, user_id: 1, venue_id: 13},
#   {is_checked_in: true, user_id: 1, venue_id: 18},
#   {is_checked_in: true, user_id: 1, venue_id: 13},
#   {is_checked_in: true, user_id: 15, venue_id: 13},
#   {is_checked_in: true, user_id: 3, venue_id: 13},
#   {is_checked_in: true, user_id: 1, venue_id: 14},
#   {is_checked_in: true, user_id: 1, venue_id: 1}
# ])
# Performance.create!([
#   {rating: nil, comment: nil, completed: true, user_id: 7, song_id: 20, venue_id: 4},
#   {rating: nil, comment: nil, completed: true, user_id: 7, song_id: 3, venue_id: 4},
#   {rating: nil, comment: nil, completed: true, user_id: 11, song_id: 1, venue_id: 4},
#   {rating: nil, comment: nil, completed: true, user_id: 7, song_id: 5, venue_id: 4},
#   {rating: nil, comment: nil, completed: false, user_id: 12, song_id: 23, venue_id: 4},
#   {rating: nil, comment: nil, completed: true, user_id: 2, song_id: 39, venue_id: 4},
#   {rating: nil, comment: nil, completed: true, user_id: 1, song_id: 18, venue_id: 4},
#   {rating: nil, comment: nil, completed: true, user_id: 4, song_id: 14, venue_id: 4},
#   {rating: nil, comment: nil, completed: true, user_id: 4, song_id: 1, venue_id: 4},
#   {rating: nil, comment: nil, completed: false, user_id: 1, song_id: 20, venue_id: 18},
#   {rating: nil, comment: nil, completed: true, user_id: 16, song_id: 39, venue_id: 14},
#   {rating: nil, comment: nil, completed: true, user_id: 16, song_id: 3, venue_id: 14},
#   {rating: nil, comment: nil, completed: false, user_id: 1, song_id: 47, venue_id: 13},
#   {rating: nil, comment: nil, completed: false, user_id: 15, song_id: 8, venue_id: 13}
# ])
# Request.create!([
#   {available: false, user_id: 11, song_id: 1, venue_id: 4, checkin_id: nil, has_requested: false},
#   {available: false, user_id: 7, song_id: 20, venue_id: 4, checkin_id: nil, has_requested: false},
#   {available: false, user_id: 7, song_id: 3, venue_id: 4, checkin_id: nil, has_requested: false},
#   {available: false, user_id: 7, song_id: 5, venue_id: 4, checkin_id: nil, has_requested: false},
#   {available: true, user_id: 14, song_id: 21, venue_id: 4, checkin_id: nil, has_requested: true},
#   {available: false, user_id: 1, song_id: 18, venue_id: 4, checkin_id: nil, has_requested: false},
#   {available: false, user_id: 12, song_id: 23, venue_id: 4, checkin_id: nil, has_requested: false},
#   {available: false, user_id: 3, song_id: 3, venue_id: 4, checkin_id: nil, has_requested: false},
#   {available: true, user_id: 8, song_id: 47, venue_id: 4, checkin_id: nil, has_requested: true},
#   {available: false, user_id: 2, song_id: 39, venue_id: 4, checkin_id: nil, has_requested: false},
#   {available: true, user_id: 13, song_id: 1, venue_id: 4, checkin_id: nil, has_requested: true},
#   {available: false, user_id: 4, song_id: 14, venue_id: 4, checkin_id: nil, has_requested: false},
#   {available: false, user_id: 11, song_id: 22, venue_id: 4, checkin_id: nil, has_requested: false},
#   {available: false, user_id: 7, song_id: 17, venue_id: 4, checkin_id: nil, has_requested: true},
#   {available: false, user_id: 11, song_id: 13, venue_id: 4, checkin_id: nil, has_requested: false},
#   {available: false, user_id: 4, song_id: 1, venue_id: 4, checkin_id: nil, has_requested: false},
#   {available: false, user_id: 4, song_id: 1, venue_id: 4, checkin_id: nil, has_requested: false},
#   {available: false, user_id: 4, song_id: 1, venue_id: 4, checkin_id: nil, has_requested: false},
#   {available: false, user_id: 4, song_id: 7, venue_id: 4, checkin_id: nil, has_requested: false},
#   {available: false, user_id: 4, song_id: 21, venue_id: 4, checkin_id: nil, has_requested: false},
#   {available: false, user_id: 1, song_id: 20, venue_id: 18, checkin_id: nil, has_requested: false},
#   {available: false, user_id: 16, song_id: 39, venue_id: 14, checkin_id: nil, has_requested: false},
#   {available: false, user_id: 16, song_id: 3, venue_id: 14, checkin_id: nil, has_requested: false},
#   {available: false, user_id: 4, song_id: 14, venue_id: 4, checkin_id: nil, has_requested: false},
#   {available: false, user_id: 4, song_id: 4, venue_id: 4, checkin_id: nil, has_requested: false},
#   {available: true, user_id: 17, song_id: 47, venue_id: 14, checkin_id: nil, has_requested: true},
#   {available: true, user_id: 3, song_id: 21, venue_id: 8, checkin_id: nil, has_requested: true},
#   {available: false, user_id: 1, song_id: 9, venue_id: 18, checkin_id: nil, has_requested: false},
#   {available: false, user_id: 1, song_id: 3, venue_id: 18, checkin_id: nil, has_requested: false},
#   {available: false, user_id: 1, song_id: 4, venue_id: 2, checkin_id: nil, has_requested: false},
#   {available: false, user_id: 1, song_id: 9, venue_id: 18, checkin_id: nil, has_requested: false},
#   {available: false, user_id: 1, song_id: 47, venue_id: 13, checkin_id: nil, has_requested: false},
#   {available: false, user_id: 15, song_id: 8, venue_id: 13, checkin_id: nil, has_requested: false},
#   {available: true, user_id: 1, song_id: 19, venue_id: 14, checkin_id: nil, has_requested: true}
# ])
# Review.create!([
#   {user_id: nil, performance_id: nil, rating: nil, content: nil, headline: nil},
#   {user_id: nil, performance_id: nil, rating: nil, content: nil, headline: nil},
#   {user_id: nil, performance_id: nil, rating: nil, content: nil, headline: nil},
#   {user_id: nil, performance_id: nil, rating: nil, content: nil, headline: nil},
#   {user_id: nil, performance_id: nil, rating: 3, content: "Adding content now for this thing....", headline: "Adding now with parameters added..."},
#   {user_id: nil, performance_id: nil, rating: 4, content: "Leaving you some content...", headline: "Sup Alpha Dog!!"},
#   {user_id: nil, performance_id: nil, rating: 5, content: "x", headline: "x"},
#   {user_id: nil, performance_id: nil, rating: nil, content: nil, headline: nil},
#   {user_id: nil, performance_id: nil, rating: 3, content: " aslkls   sdkaoke9u20-9uwq ", headline: "kjlfdassda. ;alskfao "},
#   {user_id: nil, performance_id: nil, rating: 1, content: "Context", headline: "Sup Dragon?"},
#   {user_id: 11, performance_id: 382, rating: 3, content: "A little bit pitchy tho.", headline: "It was cool."},
#   {user_id: 4, performance_id: 382, rating: 3, content: "Nice", headline: "Adding a headline. This is from P Money"},
#   {user_id: 3, performance_id: 382, rating: 5, content: "Not too bad. I like it.", headline: "This one's from relativity: aka Einstein"},
#   {user_id: 13, performance_id: 382, rating: 5, content: "ya brah...you murdered the track.", headline: "King here. Loved it."},
#   {user_id: 14, performance_id: 382, rating: 3, content: "Some content for you here...", headline: "NEO reviews this performance by Dragon!"},
#   {user_id: 11, performance_id: 384, rating: 3, content: "Loved your rendition of this song.  You're awesome!!", headline: "Excellent!!"},
#   {user_id: 11, performance_id: 384, rating: 3, content: "This is Vendetta", headline: "Can I leave a 2nd review??"},
#   {user_id: 11, performance_id: 384, rating: 3, content: "Some content...", headline: "A 3rd...from Vendetta"},
#   {user_id: 11, performance_id: 384, rating: 3, content: "Some content...", headline: "A 3rd...from Vendetta"},
#   {user_id: 11, performance_id: 384, rating: 5, content: "More content...but I'm not content", headline: "A 4th...How about it?!?"},
#   {user_id: 4, performance_id: 382, rating: 3, content: "Adding Content for u bitches...", headline: "P_Diddio reviewing Sweetback's Stout.."},
#   {user_id: 7, performance_id: 387, rating: 4, content: "It was awesome. And the dancing was cool too. Just like in that busted ass video.", headline: "Better than Drake?!?"},
#   {user_id: 7, performance_id: 388, rating: 4, content: "Some content..", headline: "Not bad dude..."},
#   {user_id: 7, performance_id: 389, rating: 5, content: "I agree", headline: "Cam...you're the greatest..."},
#   {user_id: 8, performance_id: 389, rating: 1, content: "Content", headline: "You suck dude"},
#   {user_id: 8, performance_id: 388, rating: 3, content: "Some content....", headline: "A headline..."},
#   {user_id: 8, performance_id: 389, rating: 1, content: "x", headline: "x"},
#   {user_id: 8, performance_id: 389, rating: 4, content: "", headline: ""},
#   {user_id: 8, performance_id: 388, rating: 5, content: "ffff", headline: "fff"},
#   {user_id: 8, performance_id: 389, rating: 3, content: "I think so...", headline: "Can I still leave a review?"},
#   {user_id: 15, performance_id: 390, rating: 3, content: "I really dug your performance homeboy, but Imma only give you 3 stars.", headline: "AWESOME!!!!!"},
#   {user_id: 3, performance_id: 390, rating: 1, content: "Drop the mic, you shouldn't be holdin' it", headline: "C'mon man!"},
#   {user_id: 3, performance_id: 390, rating: 5, content: nil, headline: "Man, I only got 36 characters to m.."}
# ])
Song.create!([
  {artist: "Rihanna feat. Drizzy", title: "Work", genre: "Hot 100", lyrics: "", user_id: nil, art: "Screen_Shot_2016-04-06_at_2.04.33_AM.png"},
  {artist: "Justin Bieber", title: "Love Yourself", genre: "Hot 100", lyrics: "For all the times that you rain on my parade\r\nAnd all the clubs you get in using my name\r\nYou think you broke my heart, oh, girl for goodness' sake\r\nYou think I'm crying on my own. Well, I ain't\r\n\r\nAnd I didn't wanna write a song\r\n'Cause I didn't want anyone thinking I still care. I don't,\r\nBut you still hit my phone up\r\nAnd, baby, I be movin' on\r\nAnd I think you should be somethin' I don't wanna hold back,\r\nMaybe you should know that\r\n\r\nMy mama don't like you and she likes everyone\r\nAnd I never like to admit that I was wrong\r\nAnd I've been so caught up in my job,\r\nDidn't see what's going on\r\nBut now I know,\r\nI'm better sleeping on my own\r\n\r\n'Cause if you like the way you look that much\r\nOh, baby, you should go and love yourself\r\nAnd if you think that I'm still holdin' on to somethin'\r\nYou should go and love yourself\r\n\r\nAnd when you told me that you hated my friends\r\nThe only problem was with you and not them\r\nAnd every time you told me my opinion was wrong\r\nAnd tried to make me forget where I came from\r\n\r\nAnd I didn't wanna write a song\r\n'Cause I didn't want anyone thinking I still care. I don't,\r\nBut you still hit my phone up\r\nAnd, baby, I be movin' on\r\nAnd I think you should be somethin' I don't wanna hold back,\r\nMaybe you should know that\r\n\r\nMy mama don't like you and she likes everyone\r\nAnd I never like to admit that I was wrong\r\nAnd I've been so caught up in my job,\r\nDidn't see what's going on\r\nBut now I know,\r\nI'm better sleeping on my own\r\n\r\n'Cause if you like the way you look that much\r\nOh, baby, you should go and love yourself\r\nAnd if you think that I'm still holdin' on to somethin'\r\nYou should go and love yourself\r\n\r\nFor all the times that you made me feel small\r\nI fell in love. Now I feel nothin' at all\r\nAnd never felt so low when I was vulnerable\r\nWas I a fool to let you break down my walls?\r\n\r\n'Cause if you like the way you look that much\r\nOh, baby, you should go and love yourself\r\nAnd if you think that I'm still holdin' on to somethin'\r\nYou should go and love yourself\r\n\r\n'Cause if you like the way you look that much\r\nOh, baby, you should go and love yourself\r\nAnd if you think (you think) that I'm (that I'm) still holdin' on (holdin' on) to somethin'\r\nYou should go and love yourself", user_id: nil, art: "Screen_Shot_2016-04-06_at_2.10.00_AM.png"},
  {artist: "Twenty One Pilots", title: "Stressed Out", genre: "Hot 100", lyrics: "", user_id: nil, art: "Screen_Shot_2016-04-06_at_2.11.05_AM.png"},
  {artist: "Justin Bieber", title: "Sorry", genre: "Hot 100", lyrics: "", user_id: nil, art: "Screen_Shot_2016-04-06_at_2.10.00_AM.png"},
  {artist: "Flo Rida", title: "My House", genre: "Hot 100", lyrics: "", user_id: nil, art: "Screen_Shot_2016-04-06_at_2.13.16_AM.png"},
  {artist: "Zayn", title: "Pillowtalk", genre: "Hot 100", lyrics: "", user_id: nil, art: "Screen_Shot_2016-04-06_at_2.15.00_AM.png"},
  {artist: "G-Eazy x Bebe Rexha", title: "Me, Myself & I", genre: "Hot 100", lyrics: "", user_id: nil, art: "Screen_Shot_2016-04-06_at_2.14.08_AM.png"},
  {artist: "Adele", title: "Hello", genre: "Hot 100", lyrics: "", user_id: nil, art: "Screen_Shot_2016-04-06_at_2.15.41_AM.png"},
  {artist: "DNCE", title: "Cake By The Ocean", genre: "Hot 100", lyrics: "", user_id: nil, art: "Screen_Shot_2016-04-06_at_2.16.49_AM.png"},
  {artist: "The Chainsmokers feat. Rozes", title: "Roses", genre: "Hot 100", lyrics: "", user_id: nil, art: "Screen_Shot_2016-04-06_at_2.19.11_AM.png"},
  {artist: "Selena Gomez", title: "Hands To Myself", genre: "Hot 100", lyrics: "", user_id: nil, art: "Screen_Shot_2016-04-06_at_2.17.43_AM.png"},
  {artist: "Lukas Graham", title: "7 Years", genre: "Hot 100", lyrics: "", user_id: nil, art: "Screen_Shot_2016-04-06_at_2.18.25_AM.png"},
  {artist: "Yo Gotti Featuring Nicki Minaj", title: "Down In The DM", genre: "Hot 100", lyrics: "", user_id: nil, art: "Screen_Shot_2016-04-06_at_2.29.59_AM.png"},
  {artist: "Charlie Puth", title: "One Call Away", genre: "Hot 100", lyrics: "", user_id: nil, art: "Screen_Shot_2016-04-06_at_2.25.49_AM.png"},
  {artist: "Mike Posner", title: "I Took A Pill In Ibiza", genre: "Hot 100", lyrics: "", user_id: nil, art: "Screen_Shot_2016-04-06_at_2.26.48_AM.png"},
  {artist: "Bryson Tiller", title: "Don't", genre: "Hot 100", lyrics: "", user_id: nil, art: "Screen_Shot_2016-04-06_at_2.34.18_AM.png"},
  {artist: "Adele", title: "When We Were Young", genre: "Hot 100", lyrics: "", user_id: nil, art: "Screen_Shot_2016-04-06_at_2.15.41_AM.png"},
  {artist: "Selena Gomez", title: "Same Old Love", genre: "Hot 100", lyrics: "", user_id: nil, art: "Screen_Shot_2016-04-06_at_2.17.43_AM.png"},
  {artist: "Drake", title: "Hotline Bling", genre: "Hot 100", lyrics: "", user_id: nil, art: "Screen_Shot_2016-04-06_at_2.32.39_AM.png"},
  {artist: "The Weekend", title: "The Hills", genre: "Hot 100", lyrics: "", user_id: nil, art: "Screen_Shot_2016-04-06_at_2.33.55_AM.png"},
  {artist: "Daya", title: "Hide Away", genre: "Hot 100", lyrics: "", user_id: nil, art: "Screen_Shot_2016-04-06_at_2.34.49_AM.png"},
  {artist: "Justin Bieber", title: "What Do You Mean?", genre: "Hot 100", lyrics: "", user_id: nil, art: "Screen_Shot_2016-04-06_at_9.29.32_AM.png"},
  {artist: "Shawn Mendes", title: "Stiches", genre: "Hot 100", lyrics: "\"Stitches\"\r\n\r\nI thought that I'd been hurt before\r\nBut no one's ever left me quite this sore\r\nYour words cut deeper than a knife\r\nNow I need someone to breathe me back to life...", user_id: nil, art: "Screen_Shot_2016-04-06_at_9.34.52_AM.png"},
  {artist: "Stevie Wonder", title: "Higher Ground", genre: "R&B", lyrics: "", user_id: nil, art: "Screen_Shot_2016-04-06_at_9.46.49_AM.png"}
])
User.create!([
  {email: "alpha@example.com", encrypted_password: "$2a$10$kvIGeEDNW41vOAAp/j5gEeEt3KmrMgn0Cu2rx4CV9T1737UJ10dGi", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 53, current_sign_in_at: "2016-04-11 14:15:22", last_sign_in_at: "2016-04-10 21:50:04", current_sign_in_ip: "::1", last_sign_in_ip: "::1", stagename: "Alpha_Dog", is_checked_in: true, is_in_queue: false, is_manager: true, is_admin: true, is_dj: true, has_performed: false, avatar: "Screen_Shot_2016-03-04_at_7.30.14_PM.png"},
  {email: "joe@example.com", encrypted_password: "$2a$10$D6FHWZrwDXQsgsHM/WnYY.ykWV6fvhOumTjaJqRWuXZEf//arl312", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 16, current_sign_in_at: "2016-04-08 04:14:22", last_sign_in_at: "2016-04-07 22:52:11", current_sign_in_ip: "::1", last_sign_in_ip: "::1", stagename: "joey_bag-O-Donuts", is_checked_in: true, is_in_queue: false, is_manager: false, is_admin: false, is_dj: false, has_performed: false, avatar: "donut-524558_640.jpg"},
  {email: "einstein@example.com", encrypted_password: "$2a$10$dFkc94G6LF6WAB6bF237Y.r2xA4lo5jbdbISXPiiF4W5.3uwh67b.", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 28, current_sign_in_at: "2016-04-10 22:25:22", last_sign_in_at: "2016-04-09 16:41:51", current_sign_in_ip: "::1", last_sign_in_ip: "::1", stagename: "relativity", is_checked_in: true, is_in_queue: false, is_manager: false, is_admin: false, is_dj: false, has_performed: false, avatar: "Albert.png"},
  {email: "p@example.com", encrypted_password: "$2a$10$r4KHM/Wt5YX5a2tJiyJCdOAtxLNtroQZVpU2kxa51jKt71TcYr27G", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 27, current_sign_in_at: "2016-04-09 16:12:17", last_sign_in_at: "2016-04-09 04:58:35", current_sign_in_ip: "::1", last_sign_in_ip: "::1", stagename: "P Money", is_checked_in: false, is_in_queue: false, is_manager: true, is_admin: false, is_dj: false, has_performed: false, avatar: "Screen_Shot_2016-03-28_at_4.07.34_PM.png"},
  {email: "dj@example.com", encrypted_password: "$2a$10$U2SwX2o3Prq8SgmlcGeuuOOlGcdReudfU9uxoF0h6UlRVcM.4vFcq", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 84, current_sign_in_at: "2016-04-09 16:39:14", last_sign_in_at: "2016-04-09 04:59:56", current_sign_in_ip: "::1", last_sign_in_ip: "::1", stagename: "DJPhilMac", is_checked_in: true, is_in_queue: false, is_manager: false, is_admin: false, is_dj: true, has_performed: false, avatar: "Screen_Shot_2016-03-28_at_4.12.08_PM.png"},
  {email: "beth@meanmommy.com", encrypted_password: "$2a$10$oBn4euPW3.HQSNCgMLeY4O81Vi0fQQmkUy9h96A6TBKwOeRAKEkDe", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-03-05 17:39:03", last_sign_in_at: "2016-03-05 17:39:03", current_sign_in_ip: "::1", last_sign_in_ip: "::1", stagename: "MeanGirl", is_checked_in: false, is_in_queue: false, is_manager: false, is_admin: false, is_dj: true, has_performed: false, avatar: nil},
  {email: "x@example.com", encrypted_password: "$2a$10$9mUCvmfNVmJpBZD8sgSXXOh/fF.8Ex8Bi/BkKT/e.1QcvLaI3ViM6", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 45, current_sign_in_at: "2016-04-11 03:45:00", last_sign_in_at: "2016-04-09 15:10:45", current_sign_in_ip: "::1", last_sign_in_ip: "::1", stagename: "Mind_Blowin", is_checked_in: true, is_in_queue: false, is_manager: false, is_admin: false, is_dj: false, has_performed: false, avatar: "Screen_Shot_2016-04-06_at_1.11.18_AM.png"},
  {email: "gangsta@example.com", encrypted_password: "$2a$10$TxlTeXQurW5OtIrs3H8Ll.YqEsLrCPvNzGwcdTKVbQDNE9EhWF5em", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 18, current_sign_in_at: "2016-04-09 15:51:25", last_sign_in_at: "2016-04-07 22:51:14", current_sign_in_ip: "::1", last_sign_in_ip: "::1", stagename: "Gangsta Pat", is_checked_in: true, is_in_queue: false, is_manager: false, is_admin: false, is_dj: false, has_performed: false, avatar: "gangsta-810777_640.png"},
  {email: "d@example.com", encrypted_password: "$2a$10$Q7obo6Bi/vdhgQQ.BOyh4OVs23wtujf7FoVAY5qXBEKlCmfLhpWDq", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 7, current_sign_in_at: "2016-04-07 17:07:04", last_sign_in_at: "2016-04-06 17:18:11", current_sign_in_ip: "::1", last_sign_in_ip: "::1", stagename: "DeltaDog", is_checked_in: true, is_in_queue: false, is_manager: false, is_admin: false, is_dj: false, has_performed: false, avatar: "flaming_skull.png"},
  {email: "tiger@example.com", encrypted_password: "$2a$10$KjjYdM.fSseBtrs/pn0AXODJmL8ZjlUMYeE7DCRv/wPwNngs6IaC.", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2016-04-07 22:57:37", last_sign_in_at: "2016-04-04 16:00:16", current_sign_in_ip: "::1", last_sign_in_ip: "::1", stagename: "TiggerDa", is_checked_in: true, is_in_queue: false, is_manager: false, is_admin: false, is_dj: false, has_performed: false, avatar: "Screen_Shot_2016-03-28_at_3.59.32_PM.png"},
  {email: "v@example.com", encrypted_password: "$2a$10$Wed4PA0BJivE/mTAbnKmmegzMifV9x7.vD3vFfN9a81HnqSTHcgGW", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 16, current_sign_in_at: "2016-04-09 02:47:42", last_sign_in_at: "2016-04-08 13:18:08", current_sign_in_ip: "::1", last_sign_in_ip: "::1", stagename: "Vendetta", is_checked_in: true, is_in_queue: false, is_manager: false, is_admin: false, is_dj: false, has_performed: false, avatar: "Screen_Shot_2016-03-28_at_4.02.05_PM.png"},
  {email: "bruce@example.com", encrypted_password: "$2a$10$1u3A49Vz2m.IcHbLz6MfMuaKorwzGhdMsxUQX/EN91qrpy176ofmS", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 13, current_sign_in_at: "2016-04-08 19:57:38", last_sign_in_at: "2016-04-08 03:52:22", current_sign_in_ip: "::1", last_sign_in_ip: "::1", stagename: "Dragon", is_checked_in: true, is_in_queue: false, is_manager: false, is_admin: false, is_dj: false, has_performed: false, avatar: "Screen_Shot_2016-03-28_at_4.13.55_PM.png"},
  {email: "lion@example.com", encrypted_password: "$2a$10$YGyrWdlTjTk3Mrl/h4WnseRe6cUsD5fi1he0Wu/Y1rtLR59HGbBgm", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 7, current_sign_in_at: "2016-04-09 03:27:21", last_sign_in_at: "2016-04-07 22:53:28", current_sign_in_ip: "::1", last_sign_in_ip: "::1", stagename: "King", is_checked_in: true, is_in_queue: false, is_manager: false, is_admin: false, is_dj: false, has_performed: false, avatar: "Screen_Shot_2016-03-28_at_4.09.46_PM.png"},
  {email: "neondj@example.com", encrypted_password: "$2a$10$yhjNm10Ex8yAkfjaodx4S.ZED9PXTuGuzWgI6GIRNQ8V6VlDcLsNS", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 6, current_sign_in_at: "2016-04-09 03:37:44", last_sign_in_at: "2016-04-07 22:55:23", current_sign_in_ip: "::1", last_sign_in_ip: "::1", stagename: "Neo", is_checked_in: true, is_in_queue: false, is_manager: false, is_admin: false, is_dj: false, has_performed: false, avatar: "digi_dj.jpg"},
  {email: "philmac@example.com", encrypted_password: "$2a$10$jpFQjXXblQlzL5U5kqKu.ejDk10hbysNEatcOct2hpKC0tSu.aBGu", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2016-04-10 22:17:43", last_sign_in_at: "2016-04-09 07:13:13", current_sign_in_ip: "::1", last_sign_in_ip: "::1", stagename: "Mackdaddy", is_checked_in: true, is_in_queue: nil, is_manager: nil, is_admin: nil, is_dj: nil, has_performed: nil, avatar: nil},
  {email: "cam@example.com", encrypted_password: "$2a$10$JbXh0QAzxKPjpAqdNgbUzeWeF6276GnYnjNAjKX36JG4nc69i40T.", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2016-04-09 16:09:15", last_sign_in_at: "2016-04-09 07:58:58", current_sign_in_ip: "::1", last_sign_in_ip: "::1", stagename: "Cam", is_checked_in: true, is_in_queue: nil, is_manager: nil, is_admin: nil, is_dj: nil, has_performed: nil, avatar: nil},
  {email: "asha@example.com", encrypted_password: "$2a$10$gC6aLOCapdiDxbG5D.1aHuLcVCYlL.WqpDHGL5N0MMoArxTt7HOIS", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-04-09 16:32:54", last_sign_in_at: "2016-04-09 16:32:54", current_sign_in_ip: "::1", last_sign_in_ip: "::1", stagename: "diva", is_checked_in: true, is_in_queue: nil, is_manager: nil, is_admin: nil, is_dj: nil, has_performed: nil, avatar: nil},
  {email: "dookie@example.com", encrypted_password: "$2a$10$y4AIHfVGIbmxSMijmRxxkujtPH.pdM/n2c/SkqyeM4AeMxLTtQVXy", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-04-10 03:40:11", last_sign_in_at: "2016-04-10 03:40:11", current_sign_in_ip: "::1", last_sign_in_ip: "::1", stagename: "dookie", is_checked_in: true, is_in_queue: nil, is_manager: nil, is_admin: nil, is_dj: nil, has_performed: nil, avatar: nil}
])
Venue.create!([
  {name: "Lincoln Karaoke", address: "5526 N. Lincoln Avenue", city: "Chicago", description: "Karaoke bar with private rooms featuring multiple mikes, TVs & sofas, plus cocktails & bar eats.", image: "Screen_Shot_2016-04-06_at_12.24.51_AM.png"},
  {name: "Brando's Speakeasy", address: "343 S Dearborn St", city: "Chicago", description: "Intimate lounge/club delivering drinks, karaoke & dancing in a vintage space in a historic building.", image: "Brandos_Logo.png"},
  {name: "Murasaki Saki Lounge", address: "211 E. Ontario", city: "Chicago", description: "Swanky Japanese lounge with a big sake & spirits list, a small-plates menu & a karaoke room.", image: "Screen_Shot_2016-04-06_at_12.26.28_AM.png"},
  {name: "Sakura Karaoke Lounge", address: "234 W. Cermak Rd. ", city: "Chicago", description: "Trendy subterranean karaoke lounge with cocktails, light bites & dancing amid TV displays & sofas. Basement.", image: "Screen_Shot_2016-04-06_at_12.39.42_AM.png"},
  {name: "Trader Todd's", address: "3216 N. Sheffield Ave", city: "Chicago", description: "Festive karaoke bar with a beer garden, seafood-filled bar menu & tropical cocktails.", image: "Screen_Shot_2016-04-06_at_12.38.16_AM.png"},
  {name: "Alice's Lounge", address: "3556 W. Belmont", city: "Chicago", description: "This large neighborhood tavern near the Belmont Blue Line stop in Avondale transforms from a dive where you may have to be buzzed in during the day into a packed karaoke mecca at night for a mix of young and old singers.", image: "Screen_Shot_2016-04-06_at_1.05.13_AM.png"},
  {name: "Uptown Lounge", address: "1136 W Lawrence Ave.", city: "Chicago", description: "Hip late-night local bar with 100+ beers, DJs & multiple TVs in an intimate, red-walled space.", image: "Screen_Shot_2016-04-06_at_12.40.47_AM.png"},
  {name: "The Hidden Cove", address: "5338 N Lincoln Ave", city: "Chicago", description: "This time-warp just north of the Lincoln Square strip turns into a divey hall of karaoke seven nights a week. One large main room features a large dancefloor, wood-paneled walls, old-school tube TVs, and maybe cardboard cutouts of Corona models and Dos Equis ads. And it's a 4 a.m. bar.", image: "Screen_Shot_2016-04-06_at_12.54.01_AM.png"},
  {name: "No. 18 Karaoke", address: "2201 South Wentworth Avenue", city: "Chicago", description: "Chinatown's newest private-room karaoke club, accessed through a staircase inside Little Lamb Hot Pot on Cermak and Wentworth, draws a young crowd to a neon-lit clubby space to sing American and Asian pop. Of particular note is the large food menu including Mongolian barbecue, snacks, noodle soups and other Chinese dishes, a big beverage selection featuring Chinese liquor and bottle service, and free drinking games. Also of note: Private rooms are only available in four-hour increments, running from $120-300. ", image: "Screen_Shot_2016-04-06_at_12.58.02_AM.png"},
  {name: "Spyner's Pub", address: "4623 N Western Ave", city: "Chicago", description: "This classic, divey tavern in the heart of Lincoln Square draws an eclectic crowd of neighborhoodites, lesbians, and amateur singers for karaoke on Friday and Saturday nights, cheap drink specials, free pool and free popcorn.", image: "Screen_Shot_2016-04-06_at_12.59.55_AM.png"},
  {name: "Sidekicks", address: "4424 W Montrose Ave", city: "Chicago", description: "Another Chicago neighborhood gem, Sidekicks is a cavernous, longtime working-class 4 a.m. bar in Irving Park specializing in karaoke. Look for a food window selling pizza and more, a mullet-adorned woman with a tray of test-tube shots, wood-paneled interior, and a stage and karaoke DJ booth with lots of classic rock, country and pop music.", image: "Screen_Shot_2016-04-06_at_1.01.33_AM.png"},
  {name: "15/20 Lounge", address: "2428 South Wallace", city: "Chicago", description: "Want to sing karaoke in a nightclub on the outskirts of Chinatown? This loud, loungey neon-lit club has private rooms, an eclectic crowd of young and old, decently-priced drinks, and a food menu offering Asian-themed bar snacks such as \"Everything on a Stick,\" \"Ham and Egg Instant Noodles, and a \"Fatty Beef Bao Sandwich.\" ", image: "Screen_Shot_2016-04-06_at_1.03.33_AM.png"},
  {name: "Blue Frog's Local 22", address: "22 E. Hubbard St.", city: "Chicago", description: "This sibling location to Blue Frog Bar & Grill karaoke nights, burgers and beer. Formerly called \"Blue Frog 22\" the bar and restaurant was given a whirlwind makeover during filming for a reality show on Spike called \"Bar Rescue.\" Look for a more sleek, uniform decor (no more board games on the walls) and upgraded menu of burgers and sandwiches.", image: "Screen_Shot_2016-04-09_at_12.25.18_AM.png"},
  {name: "Holiday Club", address: "4000 N. Sheridan Rd.", city: "Chicago", description: "Holiday Club, Uptown's self-proclaimed \"Swinger's Mecca\" is nostalgic for the days of fedoras, martinis and lounge acts. Vintage movie posters and a larger-than-life cut-out of the Rat Pack prove that Sinatra and his cronies may be gone, but they are not forgotten. If lounging and playing songs from the jukebox isn't your thing, try your hand at karaoke, pool, Golden Tee golf or posing for pics in the photo booth. Sate your appetite with comfort food classics such as meatloaf, mashed potatoes and mac and cheese.", image: "Screen_Shot_2016-04-09_at_12.30.18_AM.png"},
  {name: "Rockit Bar and Grill", address: "22 W. Hubbard St.", city: "Chicago", description: "The Chicago club hot shots of Rockit Ranch Productions--Billy Dec, Arturo Gomez and Brad Young--are behind this laid-back yet upscale bar and grill. But with an interior designed by Oprah pillow-fluffer Nate Berkus and a menu planned by James Gottwald, whose last gig was at Jordan's in Washington D.C., we suggest you do some primping before showing up. Entree selections include a chicken paillard, mussels and chorizo, and a Kobe beef burger. A large first-floor dining area reflects the space's past life as lamp factory: exposed beams, brick walls and a 75-foot skylight. An upstairs lounge softens things with rich browns and cremes, pool tables and plasma TVs.", image: "Screen_Shot_2016-04-09_at_12.36.19_AM.png"},
  {name: "Zachary's - Jefferson Park", address: "5368 N. Milwaukee Ave.", city: "Chicago", description: "This snug Jefferson Park hang-out features plush couches, moody blue lighting and a cityscape mural wrapping around the walls.", image: "Screen_Shot_2016-04-09_at_12.44.10_AM.png"},
  {name: "Roscoe Village Pub", address: "2159 W. Addison St", city: "Chicago", description: "This Roscoe Village spot is a small, laid-back with spot with frequent karaoke nights and drinks for a price that definitely won't break the bank.", image: "Screen_Shot_2016-04-09_at_12.48.19_AM.png"},
  {name: "Moe's Tavern", address: "2937 N. Milwaukee Ave", city: "Chicago", description: "This Logan Square spot is a laid-back neighborhood bar with superb drink specials and darts plus live music and karaoke nights.", image: "Screen_Shot_2016-04-09_at_12.55.12_AM.png"},
  {name: "Dino's", address: "6400 N Clark Street", city: "Chicago", description: "Come hang where the beer is always cold, the drinks are strong and the staff is friendly. We offer karaoke every Friday and Saturday from 9PM to close. We also have six HDTVs where you can come watch the game, including UEFA Soccer matches!", image: "Screen_Shot_2016-04-10_at_10.08.30_PM.png"},
  {name: "Friar Tuck", address: "3010 N Broadway St\u2028", city: "Chicago", description: "Friar Tuck, located in east Lakeview near Belmont and Broadway, is a well-kept secret of Chicago. This self-proclaimed “old fashioned Cheers-style pub where everybody knows your name… or at least tries to” has a great energy. The booze prices are certainly affordable with $5 mini pitchers and mixed drinks under $6. The best part about Friar Tuck? You can actually get a chance to sing! So break out your list of must-sing songs and start greasing up those pipes!", image: "Screen_Shot_2016-04-10_at_10.24.29_PM.png"}
])
